insert into public.ingredients (id,name,category,state,temperature,unlock_level,base_cost) values
('coffee_beans','커피 원두','COFFEE','RAW','AMBIENT',1,20),('ground_espresso','에스프레소용 분쇄 원두','COFFEE','GROUND','AMBIENT',1,25),('espresso_shot','에스프레소 샷','COFFEE','EXTRACT','HOT',1,45),('double_espresso','더블 에스프레소','COFFEE','EXTRACT','HOT',2,80),('cold_brew_concentrate','콜드브루 원액','COFFEE','EXTRACT','COLD',6,90),
('filtered_water','정수','WATER','LIQUID','AMBIENT',1,0),('hot_water','뜨거운 물','WATER','LIQUID','HOT',1,0),('cold_water','차가운 물','WATER','LIQUID','COLD',1,0),('sparkling_water','탄산수','WATER','LIQUID','COLD',4,25),('ice','얼음','WATER','FROZEN','COLD',2,5),
('milk','우유','DAIRY','LIQUID','COLD',1,30),('steamed_milk','스팀 밀크','DAIRY','STEAMED','HOT',1,35),('milk_foam','밀크폼','DAIRY','FOAMED','HOT',2,40),('low_fat_milk','저지방 우유','DAIRY','LIQUID','COLD',5,35),('oat_milk','오트 음료','ALT_MILK','LIQUID','COLD',6,55),('soy_milk','두유','ALT_MILK','LIQUID','COLD',7,50),('cream','생크림','DAIRY','LIQUID','COLD',5,55),
('vanilla_bean_sauce','바닐라빈 소스','SYRUP','LIQUID','AMBIENT',3,35),('caramel_sauce','캐러멜 소스','SYRUP','LIQUID','AMBIENT',3,35),('chocolate_sauce','초콜릿 소스','SYRUP','LIQUID','AMBIENT',3,35),('grapefruit_syrup','자몽청','SYRUP','LIQUID','COLD',4,45),('lemon_syrup','레몬청','SYRUP','LIQUID','COLD',4,40),
('matcha_powder','말차 파우더','POWDER','RAW','AMBIENT',5,45),('dark_chocolate_powder','다크 초콜릿 파우더','POWDER','RAW','AMBIENT',5,45),('hazelnut_powder','헤이즐넛 파우더','POWDER','RAW','AMBIENT',5,45),('mango_puree','망고 퓌레','FRUIT','LIQUID','COLD',5,50),('strawberry_puree','딸기 퓌레','FRUIT','LIQUID','COLD',5,50),
('americano_hot','아메리카노','DRINK','FINISHED','HOT',1,0),('americano_iced','아이스 아메리카노','DRINK','FINISHED','COLD',2,0),('cafe_latte_hot','카페라떼','DRINK','FINISHED','HOT',1,0),('cafe_latte_iced','아이스 카페라떼','DRINK','FINISHED','COLD',2,0),('cappuccino','카푸치노','DRINK','FINISHED','HOT',2,0),('grapefruit_aide','자몽에이드','DRINK','FINISHED','COLD',4,0),('lemon_aide','레몬에이드','DRINK','FINISHED','COLD',4,0),('vanilla_oat_cold_brew','바닐라빈 오트 콜드브루','DRINK','FINISHED','COLD',6,0),('cafe_mocha_ice_blended','카페모카 아이스 블렌디드','DRINK','FINISHED','COLD',5,0)
on conflict (id) do update set name=excluded.name, category=excluded.category, state=excluded.state, temperature=excluded.temperature, unlock_level=excluded.unlock_level, base_cost=excluded.base_cost;

insert into public.stations (id,name,process_type,unlock_level,base_duration_sec,base_slots) values
('grinder','그라인더','GRIND',1,4,1),('espresso_machine','에스프레소 머신','BREW_ESPRESSO',1,8,1),('water_dispenser','정수 디스펜서','DISPENSE',1,2,1),('kettle','온수기','HEAT',1,4,1),('ice_machine','제빙기','CHILL',2,3,1),('steam_wand','스팀 완드','STEAM',1,7,1),('milk_foamer','밀크 포머','FOAM',2,8,1),('mixer','믹싱 스테이션','MIX',1,3,1),('shaker','셰이커','SHAKE',4,5,1),('blender','블렌더','BLEND',5,9,1),('cold_brew_tower','콜드브루 타워','BREW_COLD',6,20,1)
on conflict (id) do update set name=excluded.name, process_type=excluded.process_type, unlock_level=excluded.unlock_level, base_duration_sec=excluded.base_duration_sec, base_slots=excluded.base_slots;

insert into public.processing_rules (id,station_id,process_type,input_item_id,input_quantity,output_item_id,duration_sec,unlock_level) values
('grind_espresso','grinder','GRIND','coffee_beans',1,'ground_espresso',4,1),
('extract_espresso','espresso_machine','BREW_ESPRESSO','ground_espresso',1,'espresso_shot',8,1),
('heat_water','kettle','HEAT','filtered_water',1,'hot_water',4,1),
('chill_water','ice_machine','CHILL','filtered_water',1,'cold_water',3,1),
('make_ice','ice_machine','CHILL','cold_water',1,'ice',5,2),
('steam_milk','steam_wand','STEAM','milk',1,'steamed_milk',7,1),
('foam_milk','milk_foamer','FOAM','milk',1,'milk_foam',8,2),
('brew_cold','cold_brew_tower','BREW_COLD','ground_espresso',2,'cold_brew_concentrate',20,6)
on conflict (id) do update set station_id=excluded.station_id, process_type=excluded.process_type, input_item_id=excluded.input_item_id, input_quantity=excluded.input_quantity, output_item_id=excluded.output_item_id, duration_sec=excluded.duration_sec, unlock_level=excluded.unlock_level;

insert into public.recipes (id,name,output_item_id,unlock_level,reward_gold,reward_xp) values
('americano_hot','아메리카노','americano_hot',1,180,18),('americano_iced','아이스 아메리카노','americano_iced',2,200,20),('cafe_latte_hot','카페라떼','cafe_latte_hot',1,230,24),('cafe_latte_iced','아이스 카페라떼','cafe_latte_iced',2,250,26),('cappuccino','카푸치노','cappuccino',2,260,28),('grapefruit_aide','자몽에이드','grapefruit_aide',4,280,30),('lemon_aide','레몬에이드','lemon_aide',4,270,29),('vanilla_oat_cold_brew','바닐라빈 오트 콜드브루','vanilla_oat_cold_brew',6,380,42),('cafe_mocha_ice_blended','카페모카 아이스 블렌디드','cafe_mocha_ice_blended',5,420,46)
on conflict (id) do update set name=excluded.name, output_item_id=excluded.output_item_id, unlock_level=excluded.unlock_level, reward_gold=excluded.reward_gold, reward_xp=excluded.reward_xp;

insert into public.recipe_steps (recipe_id,step_order,station_id,process_type,output_item_id,duration_sec) values
('americano_hot',1,'mixer','MIX','americano_hot',3),('americano_iced',1,'mixer','MIX','americano_iced',3),('cafe_latte_hot',1,'mixer','MIX','cafe_latte_hot',3),('cafe_latte_iced',1,'mixer','MIX','cafe_latte_iced',3),('cappuccino',1,'mixer','MIX','cappuccino',4),('grapefruit_aide',1,'shaker','SHAKE','grapefruit_aide',5),('lemon_aide',1,'shaker','SHAKE','lemon_aide',5),('vanilla_oat_cold_brew',1,'mixer','MIX','vanilla_oat_cold_brew',5),('cafe_mocha_ice_blended',1,'blender','BLEND','cafe_mocha_ice_blended',9)
on conflict (recipe_id,step_order) do update set station_id=excluded.station_id, process_type=excluded.process_type, output_item_id=excluded.output_item_id, duration_sec=excluded.duration_sec;

insert into public.recipe_step_inputs (recipe_id,step_order,ingredient_id,quantity) values
('americano_hot',1,'espresso_shot',1),('americano_hot',1,'hot_water',1),('americano_iced',1,'espresso_shot',1),('americano_iced',1,'cold_water',1),('americano_iced',1,'ice',1),('cafe_latte_hot',1,'espresso_shot',1),('cafe_latte_hot',1,'steamed_milk',1),('cafe_latte_iced',1,'espresso_shot',1),('cafe_latte_iced',1,'milk',1),('cafe_latte_iced',1,'ice',1),('cappuccino',1,'espresso_shot',1),('cappuccino',1,'steamed_milk',1),('cappuccino',1,'milk_foam',1),('grapefruit_aide',1,'grapefruit_syrup',1),('grapefruit_aide',1,'sparkling_water',1),('grapefruit_aide',1,'ice',1),('lemon_aide',1,'lemon_syrup',1),('lemon_aide',1,'sparkling_water',1),('lemon_aide',1,'ice',1),('vanilla_oat_cold_brew',1,'cold_brew_concentrate',1),('vanilla_oat_cold_brew',1,'oat_milk',1),('vanilla_oat_cold_brew',1,'vanilla_bean_sauce',1),('vanilla_oat_cold_brew',1,'ice',1),('cafe_mocha_ice_blended',1,'espresso_shot',1),('cafe_mocha_ice_blended',1,'dark_chocolate_powder',1),('cafe_mocha_ice_blended',1,'low_fat_milk',1),('cafe_mocha_ice_blended',1,'ice',2)
on conflict (recipe_id,step_order,ingredient_id) do update set quantity=excluded.quantity;

insert into public.upgrades (id,station_id,name,description,effect_type,effect_value,max_level,base_cost,cost_multiplier,unlock_level) values
('grinder_speed','grinder','고속 그라인더','분쇄 시간을 줄입니다.','SPEED',0.12,5,300,1.7,1),('espresso_speed','espresso_machine','고압 추출','에스프레소 추출 시간을 줄입니다.','SPEED',0.1,5,450,1.7,1),('espresso_slots','espresso_machine','듀얼 그룹헤드','동시에 추출 가능한 슬롯을 늘립니다.','SLOTS',1,2,1200,2,3),('steam_speed','steam_wand','파워 스팀','우유 스팀 시간을 줄입니다.','SPEED',0.1,5,500,1.7,2),('blender_speed','blender','프로 블렌더','블렌딩 시간을 줄입니다.','SPEED',0.1,5,900,1.8,5),('inventory_storage',null,'대형 냉장고','재료 보관 한도를 늘립니다.','STORAGE',1,2,450,1.9,2),('grinder_automation','grinder','반자동 그라인더','영업 중 원두를 자동으로 보충합니다.','STARTING_STOCK',1,3,1400,1.8,5),('tip_bonus',null,'단골 서비스','완벽 주문 팁을 높입니다.','TIP',0.05,5,700,1.8,3),('guest_patience',null,'편안한 대기 공간','손님 인내 시간을 늘립니다.','PATIENCE',0.08,5,800,1.8,4)
on conflict (id) do update set name=excluded.name, description=excluded.description, effect_type=excluded.effect_type, effect_value=excluded.effect_value, max_level=excluded.max_level, base_cost=excluded.base_cost, cost_multiplier=excluded.cost_multiplier, unlock_level=excluded.unlock_level;
