import { useEffect, useMemo, useState } from "react";
import { createSoundPlayer } from "../audio/soundPlayer";
import { getNextAction, isPreparationComplete } from "../engine/baristaEngine";
import type { AuthUser } from "../services/authService";
import type { BaristaActionId, BaristaRecipe, GameState } from "../types/game";
import { GameIcon } from "./GameIcon";

type Props = Readonly<{ state: GameState; currentUser: AuthUser | null; recipes: readonly BaristaRecipe[]; stationLevels: Readonly<Record<string, number>>; onSelectOrder: (id: string) => void; onAction: (id: BaristaActionId, recipe: BaristaRecipe) => boolean; onServe: (recipe: BaristaRecipe) => boolean; onMistake: () => void; onExit: () => void }>;
const labels: Readonly<Record<BaristaActionId, string>> = { coffee_beans: "원두", grind: "그라인더", extract: "에스프레소 머신", hot_water: "뜨거운 물", cold_water: "차가운 물", ice: "얼음", milk: "우유", steam: "스팀 완드", grapefruit_syrup: "자몽청", sparkling_water: "탄산수", cold_brew: "콜드브루 원액", vanilla_bean_sauce: "바닐라빈 소스", oat_milk: "오트 음료" };
const ingredients: readonly BaristaActionId[] = ["coffee_beans", "hot_water", "cold_water", "ice", "milk", "grapefruit_syrup", "sparkling_water", "cold_brew", "vanilla_bean_sauce", "oat_milk"];
const stations: readonly BaristaActionId[] = ["grind", "extract", "steam"];
const menuName = (id: string) => id === "americano_hot" ? "아메리카노" : id === "americano_iced" ? "아이스 아메리카노" : id === "cafe_latte_hot" ? "카페라떼" : id === "grapefruit_aide" ? "자몽에이드" : "바닐라빈 오트 콜드브루";
const durationFor = (id: BaristaActionId, levels: Readonly<Record<string, number>>) => { const base = id === "grind" ? 2600 : id === "extract" ? 3200 : id === "steam" ? 3000 : 550; const level = id === "grind" ? levels.grinder_speed ?? 0 : id === "extract" ? levels.espresso_speed ?? 0 : id === "steam" ? levels.steam_speed ?? 0 : 0; return Math.max(400, Math.round(base * (1 - level * .12))); };
const choicesFor = (correct: BaristaActionId, step: number): readonly BaristaActionId[] => { const pool = stations.includes(correct) ? stations : ingredients; const alternatives = pool.filter((item) => item !== correct); const picked = Array.from({ length: 3 }, (_, index) => alternatives[(step * 3 + index) % alternatives.length]!).filter((item, index, all) => all.indexOf(item) === index); return [correct, ...picked].sort((a, b) => ((a.charCodeAt(0) + step) % 7) - ((b.charCodeAt(0) + step) % 7)); };
const formatTime = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;

export const ChoiceBaristaCounter = ({ state, currentUser, recipes, stationLevels, onSelectOrder, onAction, onServe, onMistake, onExit }: Props) => {
  const [working, setWorking] = useState<BaristaActionId | null>(null);
  const [exitOpen, setExitOpen] = useState(false);
  const [combo, setCombo] = useState(0);
  const [feedback, setFeedback] = useState<string | null>(null);
  const sound = useMemo(() => createSoundPlayer(), []);
  useEffect(() => () => void sound.dispose(), [sound]);
  const recipe = state.preparation ? recipes.find((item) => item.itemId === state.preparation?.itemId) ?? null : null;
  const next = state.preparation && recipe ? getNextAction(state.preparation, recipe) : null;
  const complete = Boolean(state.preparation && recipe && isPreparationComplete(state.preparation, recipe));
  const step = state.preparation?.completedSteps.length ?? 0;
  const choices = next ? choicesFor(next, step) : [];
  const choose = (selected: BaristaActionId) => { if (!next || !recipe || working) return; if (selected !== next) { setCombo(0); setFeedback("잘못된 선택 · 3초 감소"); onMistake(); return; } setWorking(selected); setFeedback(null); window.setTimeout(() => { if (onAction(selected, recipe)) { sound.playMergeSound(); setCombo((value) => value + 1); } setWorking(null); }, durationFor(selected, stationLevels)); };

  return <main className="mx-auto flex h-dvh w-full max-w-[480px] flex-col overflow-hidden bg-[#F6F3EE] text-[#293A33]">
    <header className="flex items-center justify-between border-b border-[#E3DED6] bg-white px-4 pb-3 pt-[max(.75rem,env(safe-area-inset-top))]"><button className="min-h-10 rounded-xl border border-[#DED9D1] px-3 text-xs font-bold" onClick={() => setExitOpen(true)} type="button">영업 나가기</button><div className="text-center"><p className="text-[9px] font-black tracking-[.18em] text-[#82948A]">COFFEE TOWN</p><p className="text-xs font-black">Lv.{state.level} {currentUser?.displayName ?? "게스트"}</p></div><div className="text-right"><p className="font-black tabular-nums text-[#355E4D]">{formatTime(state.remainingTimeSec)}</p><p className="text-[10px] font-bold text-[#9A7435]">{state.gold} G</p></div></header>
    <section className="flex min-h-0 flex-1 flex-col p-4">
      {!state.preparation ? <><div><p className="text-xs font-black tracking-[.14em] text-[#82948A]">ORDER QUEUE</p><h1 className="mt-1 text-2xl font-black">어떤 주문부터 만들까요?</h1></div><div className="mt-4 grid min-h-0 flex-1 gap-3">{state.orders.map((order) => <button className="ui-card flex items-center gap-4 rounded-[1.5rem] border border-[#E0DBD3] bg-white px-5 text-left shadow-[0_8px_22px_rgba(44,56,49,.07)]" key={order.id} onClick={() => onSelectOrder(order.id)} type="button"><GameIcon itemId={order.itemId} className="size-14"/><div className="min-w-0 flex-1"><p className="text-xs font-bold text-[#829087]">{order.customerName}님의 주문</p><h2 className="truncate text-lg font-black">{menuName(order.itemId)}</h2><p className="text-xs font-bold text-[#9A7435]">{order.reward} G · {order.rewardXp} XP</p></div></button>)}</div></> : <><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[#829087]">{state.orders.find((order) => order.id === state.preparation?.orderId)?.customerName}님의 주문</p><h1 className="text-2xl font-black">{recipe?.name}</h1></div><div className="text-right"><p className="text-xs font-bold text-[#829087]">COMBO</p><p className="text-xl font-black text-[#B07B35]">{combo}</p></div></div><div className="mt-3 flex gap-1.5">{recipe?.steps.map((recipeStep, index) => <span className={`h-2 flex-1 rounded-full ${index < step ? "bg-[#6F9B82]" : index === step ? "animate-pulse bg-[#E2BD73]" : "bg-[#DDE1DE]"}`} key={`${recipeStep}-${index}`}/>)}</div><div className="flex flex-1 flex-col items-center justify-center"><p className="text-xs font-black tracking-[.14em] text-[#82948A]">{complete ? "PICKUP" : stations.includes(next!) ? "장비를 선택하세요" : "재료를 선택하세요"}</p>{complete ? <><GameIcon itemId={state.preparation.itemId} className="my-5 size-28"/><h2 className="text-2xl font-black">제조 완료</h2></> : <div className="mt-5 grid w-full grid-cols-2 gap-3">{choices.map((choice) => <button className={`relative min-h-28 rounded-[1.4rem] border bg-white p-3 font-black shadow-[0_6px_18px_rgba(45,58,52,.07)] ${working === choice ? "animate-pulse border-[#6D947F] bg-[#E6EFE9]" : "border-[#DDD8D0]"}`} disabled={working !== null} key={choice} onClick={() => choose(choice)} type="button"><GameIcon itemId={choice} className="mx-auto size-12"/><span className="mt-2 block text-sm">{labels[choice]}</span>{working === choice ? <span className="absolute inset-x-3 bottom-2 h-1 overflow-hidden rounded-full bg-[#D5DDD7]"><span className="block h-full animate-[station-progress_3.2s_linear] bg-[#527963]"/></span> : null}</button>)}</div>}<p className="mt-3 min-h-5 text-xs font-bold text-[#A45248]" role="status">{feedback}</p></div>{complete && recipe ? <button className="min-h-15 w-full rounded-2xl bg-[#355E4D] text-lg font-black text-white" onClick={() => { if (onServe(recipe)) { sound.playMergeSound(); setCombo(0); } }} type="button">픽업대로 전달</button> : null}</>}
    </section>
    {exitOpen ? <div className="fixed inset-0 z-50 grid place-items-end bg-black/45 p-3"><section className="w-full max-w-sm rounded-[1.75rem] bg-white p-5"><h2 className="text-xl font-black">영업을 중단할까요?</h2><p className="mt-2 text-sm leading-6 text-[#717C76]">이번 영업에서 획득한 골드와 경험치는 모두 사라집니다.</p><button className="mt-5 min-h-13 w-full rounded-2xl bg-[#A54F45] font-bold text-white" onClick={onExit} type="button">보상 포기하고 나가기</button><button className="mt-2 min-h-12 w-full rounded-2xl bg-[#EEF1EE] font-bold" onClick={() => setExitOpen(false)} type="button">계속 플레이</button></section></div> : null}
  </main>;
};
