-- Authoritative, read-only gameplay combination catalog.
create table if not exists public.recipe_combinations (
  id bigint generated by default as identity primary key,
  input_a text not null,
  input_b text not null,
  output_item text not null unique,
  sort_order integer not null unique,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint recipe_inputs_differ check (input_a <> input_b)
);

alter table public.recipe_combinations enable row level security;
revoke all on table public.recipe_combinations from anon, authenticated;
grant select on table public.recipe_combinations to anon, authenticated;
drop policy if exists "recipe_combinations_read" on public.recipe_combinations;
create policy "recipe_combinations_read" on public.recipe_combinations for select to anon, authenticated using (enabled);

insert into public.recipe_combinations (input_a,input_b,output_item,sort_order) values
('espresso','cup','espresso_cup',1),
('espresso_cup','hot_water','americano',2),
('iced_cup','espresso','iced_espresso_base',3),
('iced_espresso_base','cold_water','iced_americano',4),
('espresso_cup','steamed_milk','latte',5),
('iced_cup','milk','iced_milk_base',6),
('iced_milk_base','espresso','iced_latte',7),
('espresso_cup','vanilla_syrup','vanilla_espresso',8),
('vanilla_espresso','steamed_milk','vanilla_latte',9),
('espresso_cup','chocolate_sauce','mocha_base',10),
('mocha_base','steamed_milk','mocha',11),
('cup','vanilla_syrup','vanilla_cup',12),
('vanilla_cup','steamed_milk','vanilla_milk_cup',13),
('vanilla_milk_cup','espresso','caramel_base',14),
('caramel_base','caramel_sauce','caramel_macchiato',15),
('cup','ice','iced_cup',16),
('iced_cup','lemon_syrup','lemon_base',17),
('lemon_base','sparkling_water','lemonade',18),
('iced_cup','grapefruit_syrup','grapefruit_base',19),
('grapefruit_base','sparkling_water','grapefruitade',20),
('cup','yuzu_syrup','yuzu_base',21),
('yuzu_base','hot_water','yuzu_tea',22),
('cup','matcha_powder','matcha_cup',23),
('matcha_cup','steamed_milk','matcha_latte',24),
('cup','chocolate_sauce','chocolate_cup',25),
('chocolate_cup','steamed_milk','chocolate_latte',26),
('iced_cup','cold_brew_concentrate','cold_brew_base',27),
('cold_brew_base','cold_water','cold_brew',28),
('iced_cup','oat_milk','oat_cup',29),
('oat_cup','cold_brew_concentrate','oat_cold_brew_base',30),
('oat_cold_brew_base','vanilla_bean','vanilla_oat_cold_brew',31),
('iced_latte','chocolate_sauce','blended_base_3',32)
on conflict (output_item) do update set
  input_a=excluded.input_a,
  input_b=excluded.input_b,
  sort_order=excluded.sort_order,
  enabled=true,
  updated_at=now();
